[rewrite_local]
https?:\/\/(www\.)?haijiao\.com\/api\/(banner\/banner_list|attachment|topic\/\d+) url script-response-body haijiao.js
https?:\/\/ts\d+\.hj\d+\.top\/.*\.m3u8$ url script-response-body haijiao.js
[mitm]
hostname = *haijiao*,*hj260302818.top