#!name=One1
#!desc=One App multi-client (Egern) - bootstrap/list/detail/adblock
#!category=Media
#!author=whylkk

[MitM]
hostname = api.*, *.einhn4.com, *.em1oifd0.com, *.xqjby.com, *.scycjz.com, 38.46.10.*, 202.95.22.*, 198.44.248.*, 122.10.20.249

[URL Rewrite]
^https://.*/v2\.5/ad/space reject

[Script]
http-response ^https?://[^/]+/v2\.5/bootstrap script-path=https://cdn.jsdelivr.net/gh/whylkk/one-tk@0679e78c8fe53a3a76e88824d3f5d8cae320b4f8/one1.js, requires-body=1, timeout=30, tag=One1-Bootstrap
http-response ^https?://[^/]+/v2\.5/vip/download script-path=https://cdn.jsdelivr.net/gh/whylkk/one-tk@0679e78c8fe53a3a76e88824d3f5d8cae320b4f8/one1.js, requires-body=1, timeout=30, tag=One1-VipDL
http-response ^https?://[^/]+/v2\.5/article/detail script-path=https://cdn.jsdelivr.net/gh/whylkk/one-tk@0679e78c8fe53a3a76e88824d3f5d8cae320b4f8/one1.js, requires-body=1, timeout=30, tag=One1-Detail
http-response ^https?://[^/]+/v2\.5/article/(day|discovery|search|list) script-path=https://cdn.jsdelivr.net/gh/whylkk/one-tk@0679e78c8fe53a3a76e88824d3f5d8cae320b4f8/one1.js, requires-body=1, timeout=30, tag=One1-List
http-response ^https?://[^/]+/v2\.5/series/(list|chapters) script-path=https://cdn.jsdelivr.net/gh/whylkk/one-tk@0679e78c8fe53a3a76e88824d3f5d8cae320b4f8/one1.js, requires-body=1, timeout=30, tag=One1-Series
